# Diagnostic Netlify config — wypisze node version, używa npm ci
[build]
  command = "node -v && npm ci && npm run build"
  publish = "dist"

[build.environment]
  # Wymuś Node 20.x — Netlify rozpoznaje tu wartości typu "20" lub "20.19.0"
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200